### ISSUE TITLE
Some Platforms are no longer working due to changes with Archive.org

### ISSUE THREAD

**Issue by Jlmbles** [Koston-0xDEADBEEF/MiSTer-ROMweasel#5] opened 2024-09-15 00:05 UTC
Some platforms such as Playstation are no longer working, as files are locked and an account is now required to download them.

**Comment by Koston-0xDEADBEEF** [comment] 2024-09-16 10:38
Thanks for the report, it's appreciated.

I've deliberately left out any "download all ROMs" options from ROMweasel to avoid unnecessary load on archive.org bandwidth and I'm quite sure we're not the cause for the lockdown. I'm also not willing to do what update_all MAME ROM downloader did, which was to upload a new dedicated repository to archive.org to circumvent the lock. Instead, I'll adopt the proper fix from update_all, which adds support for setting a login username and password for downloading from locked repositories.

**Comment by Koston-0xDEADBEEF** [comment] 2024-09-16 12:27
Preliminary fix committed: https://github.com/Koston-0xDEADBEEF/MiSTer-ROMweasel/commit/24d295d170c662088ab12998e85da3e79f88f9dd

I'm closing this issue now, because my time/interest for maintaining this project is limited. Let me know if there's something fundamentally broken, besides not dealing properly with failures from attempting to use locked repos without login.

**Closed by Koston-0xDEADBEEF** 2024-09-16 12:27 UTC
